# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [2]:
import numpy as np
# Your code here
def random_matrix(n,m):
    return np.random.randint(1,10,(n,m))

In [4]:
A = random_matrix(4,3)
A

array([[9, 5, 9],
       [6, 2, 5],
       [4, 4, 4],
       [4, 9, 6]])

In [5]:
B = random_matrix(3,5)
B

array([[2, 6, 9, 3, 4],
       [9, 2, 7, 6, 4],
       [6, 1, 5, 8, 5]])

In [8]:
C = random_matrix(3,5)
C

array([[7, 6, 4, 8, 6],
       [1, 8, 3, 9, 8],
       [6, 8, 6, 7, 1]])

In [10]:
LHS = A.dot(B+C)
LHS

array([[239, 239, 266, 309, 204],
       [134, 137, 153, 171, 114],
       [124, 124, 136, 164, 112],
       [198, 192, 208, 269, 184]])

In [12]:
RHS = A.dot(B) + A.dot(C)
RHS

array([[239, 239, 266, 309, 204],
       [134, 137, 153, 171, 114],
       [124, 124, 136, 164, 112],
       [198, 192, 208, 269, 184]])

In [13]:
LHS == RHS

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [15]:
# Your code here 
B = random_matrix(3,2)
C = random_matrix(2,3)
A.dot(B.dot(C))

array([[2111, 2111,  457],
       [1168, 1168,  251],
       [1180, 1180,  260],
       [1976, 1976,  442]])

In [16]:
(A.dot(B)).dot(C)

array([[2111, 2111,  457],
       [1168, 1168,  251],
       [1180, 1180,  260],
       [1976, 1976,  442]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [19]:
# Your code here 
A = random_matrix(5,3)
B = random_matrix(3,5)

In [20]:
B.dot(A)

array([[117, 118, 118],
       [114, 124, 134],
       [151, 189, 128]])

In [21]:
A.dot(B)

array([[ 60,  97, 106,  40,  68],
       [ 73,  47,  83,  35,  68],
       [ 74, 102, 141,  54,  92],
       [ 47,  76,  66,  25,  44],
       [ 89, 124, 143,  55,  96]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [23]:
# Your code here
X = random_matrix(3,3)
y = random_matrix(3,1)
print(X)
print(y)

[[3 2 2]
 [6 2 5]
 [8 5 7]]
[[2]
 [5]
 [4]]


In [24]:
X.T.dot(y)

array([[68],
       [34],
       [57]])

In [25]:
y.T.dot(X)

array([[68, 34, 57]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [28]:
# Your code here 
A.dot(B).T

array([[ 60,  73,  74,  47,  89],
       [ 97,  47, 102,  76, 124],
       [106,  83, 141,  66, 143],
       [ 40,  35,  54,  25,  55],
       [ 68,  68,  92,  44,  96]])

In [29]:
(B.T).dot(A.T)

array([[ 60,  73,  74,  47,  89],
       [ 97,  47, 102,  76, 124],
       [106,  83, 141,  66, 143],
       [ 40,  35,  54,  25,  55],
       [ 68,  68,  92,  44,  96]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 